import type { Encounter, EncounterNode, LearningModule, LessonSection, Metrics, QuizQuestion, Village } from './types';
import type { LearningLab } from './learning-labs';

const metricKeys = ['latency', 'availability', 'consistency', 'throughput', 'complexity'] as const;
const initial: Metrics = { latency: 45, availability: 60, consistency: 60, throughput: 45, complexity: 35 };
const guide = 'Scenario scores are qualitative values from 0 to 100. Higher availability, consistency and throughput are better; lower latency and complexity are better. These are teaching signals, not production measurements.';
type Turn = { prompt: string; context: string; tag: string; good: string; bad: string; goodFeedback: string; badFeedback: string };
const effects = (good: boolean, index: number): Partial<Metrics> => good
  ? { consistency: index === 1 ? 7 : 3, availability: index === 2 ? 5 : 2, throughput: 3, latency: index === 0 ? 2 : -2, complexity: 2 }
  : { consistency: -7, availability: -4, throughput: -3, latency: 4, complexity: 5 };
const describe = (state: Metrics) => metricKeys.map(key => `${key}=${state[key]}`).join(', ');
const apply = (state: Metrics, next: Partial<Metrics>): Metrics => Object.fromEntries(metricKeys.map(key => [key, Math.max(0, Math.min(100, state[key] + (next[key] ?? 0)))])) as Metrics;
function encounter(id: string, name: string, kind: Encounter['kind'], intro: string, turns: Turn[], reflectionPrompt: string, timeLimitSeconds?: number): Encounter {
  const nodes: EncounterNode[] = [];
  const visit = (index: number, state: Metrics): string => {
    const turn = turns[index], nodeId = `${id}-en-${index + 1}`;
    const goodEffects = effects(true, index), badEffects = effects(false, index);
    const nextGood = apply(state, goodEffects), nextBad = apply(state, badEffects);
    const nextId = index === turns.length - 1 ? null : visit(index + 1, nextGood);
    nodes.push({
      id: nodeId,
      prompt: `Turn ${index + 1}/${turns.length}: ${turn.prompt}`,
      context: `${turn.context}\n${guide}\nCurrent state: ${describe(state)}.`,
      choices: [
        { id: `${nodeId}-good`, label: turn.good, correct: true, feedback: `${turn.goodFeedback} State after choice: ${describe(nextGood)}.`, effects: goodEffects, tags: [turn.tag], next: nextId },
        { id: `${nodeId}-bad`, label: turn.bad, correct: false, feedback: `${turn.badFeedback} State after choice: ${describe(nextBad)}.`, effects: badEffects, tags: [turn.tag], next: nextId },
      ],
    });
    return nodeId;
  };
  const start = visit(0, { ...initial });
  return { id, name, kind, intro: `${intro}\n${guide}`, start, nodes, initial: { ...initial }, reflectionPrompt, timeLimitSeconds };
}
const section = (title: string, body: string, example: string, takeaway: string): LessonSection => ({ title, body, example, takeaway });
const q = (id: string, prompt: string, answer: string, a: string, b: string, c: string, explanation: string, tag: string): QuizQuestion => ({ id, prompt, options: [answer, a, b, c], answer: 0, explanation, tag });
const lab = (title: string, task: string, label: string, unit: string, modes: string[], run: LearningLab['run'], range: Partial<Pick<LearningLab, 'min' | 'max' | 'initial'>> = {}): LearningLab => ({ title, task, label, unit, min: range.min ?? 0, max: range.max ?? 100, initial: range.initial ?? 50, modes, run });

export const englishModules: Record<string, Pick<LearningModule, 'sections' | 'quiz' | 'encounter'>> = {
  intro: {
    sections: [
      section('Know what the interview is testing', 'A system design interview rewards how you navigate ambiguity, connect product behavior to technical choices, explain tradeoffs and adapt when constraints change. The goal is to reason from requirements, not to recite a memorized diagram.', 'If the prompt is chat, first clarify whether the interviewer wants class design, product behavior, realtime delivery, storage, or scaling. The answer shape changes with that boundary.', 'Confirm the problem type and show reasoning before naming technologies.'),
      section('Start with behavior, then architecture', 'Describe what the user does, what state changes and what the user sees next. A design with many components can still fail if there is no durable write path or no clear read path.', 'For a bulletin board, trace post creation from button click to durable storage and back to the author view before adding queues or cache.', 'Prove one full behavior before adding supporting components.'),
      section('Clarify requirements that change the design', 'Separate functional requirements from non-functional requirements. Fast is not specific; read within two seconds and tolerate ten seconds of staleness is specific enough to shape a design.', 'A normal feed item may be stale for ten seconds, but the author may need to see their own edit immediately. That can justify a special author read path.', 'Ask questions that can change the architecture.'),
    ],
    quiz: [
      q('intro-en-q1', 'The prompt says the feed should be fast. What should you clarify first?', 'Who reads which data, and what latency or staleness is acceptable?', 'Which database logo looks best?', 'Whether every feature can use three queues', 'The Kubernetes cluster name', 'Latency and freshness targets determine the read path; implementation details come later.', 'requirements'),
      q('intro-en-q2', 'A design has cache, queue and workers, but no durable write point. What is missing?', 'A complete write flow with a clear success boundary', 'A CDN in front of workers', 'A new hashing algorithm for icons', 'A third cloud region before defining data', 'The interviewer needs to know when data is committed and when success is returned.', 'end-to-end'),
      q('intro-en-q3', 'A user can edit their own post. What kind of requirement is this?', 'A functional requirement with an ownership rule to clarify', 'Only a throughput target', 'Only a disk assumption', 'A p99 latency commitment', 'It describes an action and permission boundary, not capacity.', 'requirements'),
      q('intro-en-q4', 'The interviewer says authors must read their own edits immediately. What should you do?', 'Revisit the author read path and explain the cache tradeoff', 'Claim cache is always strongly consistent', 'Drop the read requirement', 'Rename Redis to SQL without changing the flow', 'New information changes the conditions under which the design is correct.', 'tradeoffs'),
      q('intro-en-q5', 'What is the strongest reason to add read replicas?', 'Measured read load is saturating the primary and stale reads are acceptable', 'A famous company diagram uses replicas', 'The number of services is odd', 'Every small system needs multiple regions', 'A bottleneck plus an acceptable consistency tradeoff makes the decision defensible.', 'evidence'),
    ],
    encounter: encounter('intro-fog', 'Fog of Memorization', 'fog', 'A small marketplace board needs posting and reading. The challenge changes requirements to expose memorized answers.', [
      { prompt: 'The owner asks for everything to be fast. What do you lock down?', context: 'You have limited interview time and no target behavior yet.', tag: 'requirements', good: 'Clarify post and read flows plus acceptable staleness', bad: 'Add chat, video and recommendations immediately', goodFeedback: 'The scope becomes testable and the design has a target.', badFeedback: 'The design grows before the core behavior is understood.' },
      { prompt: 'Where should the Post button return success?', context: 'The process can crash right after the response.', tag: 'durability', good: 'Return success after durable storage confirms the write', bad: 'Return success after placing the post in process memory', goodFeedback: 'The success boundary now matches what the system can recover.', badFeedback: 'A crash can lose data that was already promised to the user.' },
      { prompt: 'The author cannot see a new post right away. What do you change?', context: 'The author path may be reading stale cached data.', tag: 'tradeoffs', good: 'Read the author view from the source of truth or a fresh version', bad: 'Hide the issue with a generic syncing message', goodFeedback: 'The requirement is tied to a concrete read path.', badFeedback: 'The message does not change the data the user observes.' },
    ], 'Explain one clarified requirement, the write success boundary and one tradeoff you would measure.'),
  },
  delivery: {
    sections: [
      section('Use milestones to lead the discussion', 'A useful path is requirements, core entities, API or system interface, data flow when needed, high-level design and deep dives. The framework is a guide rail, not a ceremony.', 'For a meal ordering service, MenuItem, Order and Customer are enough to start API design. Decorative fields can wait until the state changes are clear.', 'Each milestone should make the next decision easier.'),
      section('Connect the contract to state changes', 'An API promise is useful only when the backend flow can keep it. For each behavior, show authorization, persistence, reads and failure handling.', 'POST /orders should check inventory, create the order and return an orderId. If the response is lost, the contract should let the client recover or retry safely.', 'A reliable API includes both success and failure behavior.'),
      section('Spend deep-dive time on risk', 'Deep dives should target the part most likely to break the promise: contention, fanout, durability, latency or consistency. Estimate only when the number changes a choice.', 'If lunch traffic can oversell the last meal, spend time on atomic inventory updates before calculating yearly storage.', 'Prioritize the risk that can invalidate the product behavior.'),
    ],
    quiz: [
      q('delivery-en-q1', 'After choosing three meal-ordering features, what creates shared vocabulary fastest?', 'List MenuItem, Order, Customer and key relationships', 'Pick every audit field for ten years', 'Compare six cloud providers', 'Design image compression for meals', 'Core entities support API discussion without freezing the final schema.', 'entities'),
      q('delivery-en-q2', 'Eight minutes remain and orders can oversell inventory. What should you deep dive?', 'The conditional inventory update and order creation path', 'A prettier backup domain name', 'Dashboard colors', 'Menu icons', 'Overselling violates the main requirement, so it deserves deep-dive time.', 'prioritization'),
      q('delivery-en-q3', 'Which estimate can change a cache decision?', 'The hot menu size compared with available memory', 'The character count of service names', 'Total requests without time distribution', 'The number of boxes in the diagram', 'Hot set size tells you whether cache capacity is plausible.', 'estimation'),
      q('delivery-en-q4', 'When is a high-level design ready for deep dives?', 'Each main feature has an input, state change and returned result', 'There are at least ten boxes', 'Every future index is chosen', 'Every remembered technology was mentioned', 'The design needs a working baseline before deeper constraints are tested.', 'end-to-end'),
      q('delivery-en-q5', 'A rewards system is requested halfway through. What is the best response?', 'Confirm priority and defer it unless it changes the core flow', 'Accept it silently and lose the original scope', 'Delete ordering from the design', 'Add a queue only because the word reward appears', 'Scope changes should be negotiated against the interview goal and remaining time.', 'scope'),
    ],
    encounter: encounter('delivery-scope', 'Scope Creep Beast', 'scope', 'A food-ordering prompt keeps growing while the clock is running.', [
      { prompt: 'The interviewer adds coupons, ratings and loyalty points. What do you do?', context: 'You still need a working core design.', tag: 'scope', good: 'Pick the three core functional requirements and name deferred features', bad: 'Accept every feature as in scope', goodFeedback: 'The conversation gets a clear target.', badFeedback: 'The design loses focus and core correctness suffers.' },
      { prompt: 'What interface do you design first?', context: 'The user must place an order and check status.', tag: 'api', good: 'Define create order and get order status contracts', bad: 'Start with internal worker APIs only', goodFeedback: 'The user-facing promise is now visible.', badFeedback: 'Internal plumbing appears before the product contract.' },
      { prompt: 'What gets the last deep-dive minutes?', context: 'Inventory can be contested at peak lunch.', tag: 'contention', good: 'Deep dive atomic inventory reservation and idempotent retries', bad: 'Spend the time naming every deployment box', goodFeedback: 'The risky invariant is addressed.', badFeedback: 'The diagram gets labels while the failure remains.' },
    ], 'Walk through your first eight minutes for a Twitter-like prompt: requirements, entities, API and communication style.'),
  },
  networking: {
    sections: [
      section('Choose communication by interaction shape', 'HTTP request-response is a strong default. Polling, SSE, WebSocket and gRPC serve different needs around direction, latency, streaming and internal contracts.', 'A scoreboard can use SSE for one-way updates. A collaborative editor may need WebSocket. Internal typed service calls can use gRPC.', 'Match the protocol to the interaction, not to fashion.'),
      section('Treat latency and failure as part of the design', 'DNS, TLS, geographic distance, timeouts and retries shape user experience. Retries need backoff and jitter; persistent connections need reconnect rules.', 'A regional outage can turn automatic reconnect into a storm if every client retries at once.', 'Draw the failure path as carefully as the success path.'),
    ],
    quiz: [
      q('networking-en-q1', 'A one-way live scoreboard updates when data changes. Which option is often a good fit?', 'SSE', 'Offset pagination', 'A write-only database index', 'A cron job per viewer', 'SSE supports server-to-client event streams over HTTP.', 'transport'),
      q('networking-en-q2', 'Why add jitter to retries?', 'To avoid many clients retrying at the same instant', 'To make responses strongly consistent', 'To remove timeouts', 'To encrypt DNS records', 'Jitter spreads retry load and reduces retry storms.', 'retry'),
      q('networking-en-q3', 'What is L7 load balancing aware of?', 'Application-level information such as HTTP paths or headers', 'Only electrical voltage', 'Only raw IP packets with no request context', 'Only disk layout', 'Layer 7 balancing can route based on application protocol details.', 'load-balancing'),
      q('networking-en-q4', 'A user far from the region sees high latency. What should you examine?', 'Geography, edge placement and cross-region paths', 'Only table names', 'Only object key length', 'Only CSS colors', 'Physical distance and network hops often dominate latency.', 'latency'),
      q('networking-en-q5', 'What can a persistent connection create during recovery?', 'A reconnect storm', 'Automatic perfect availability', 'A free database shard', 'A stronger B-tree', 'Many clients reconnecting together can overload the system.', 'connections'),
    ],
    encounter: encounter('network-ghost', 'Connection Ghost', 'ghost', 'Realtime clients reconnect while latency and capacity shift.', [
      { prompt: 'How do clients recover after a disconnect?', context: 'Ten thousand clients may reconnect together.', tag: 'retry', good: 'Use backoff, jitter and resume tokens', bad: 'Retry every 100 ms forever', goodFeedback: 'Recovery load is spread and resumable.', badFeedback: 'The recovery behavior becomes a denial of service against your own system.' },
      { prompt: 'Which transport fits one-way updates?', context: 'The server pushes status updates; clients do not send chat messages.', tag: 'transport', good: 'Use SSE with reconnect handling', bad: 'Require bidirectional WebSocket for every client', goodFeedback: 'The protocol matches the interaction.', badFeedback: 'The system takes on extra connection complexity.' },
      { prompt: 'Where do you route global traffic?', context: 'Users are split across regions.', tag: 'latency', good: 'Route to nearby healthy regions and define failover behavior', bad: 'Send every request to one distant region', goodFeedback: 'Latency and availability are both considered.', badFeedback: 'Distance and failure blast radius remain large.' },
    ], 'Explain your timeout, retry and connection strategy for a realtime feature.'),
  },
  api: {
    sections: [
      section('Design a contract, not just endpoints', 'REST is a solid public default when resources are clear. Actions, RPC and GraphQL can fit specific cases, but every contract needs pagination, errors, auth, idempotency and versioning.', 'POST /payments with an Idempotency-Key lets the client retry after a timeout without charging twice.', 'The API should say what is promised and how retries behave.'),
      section('Pagination must survive change', 'Offset pagination is simple but unstable when new rows arrive. Cursor pagination uses a stable ordering key so the next page starts after a known item.', 'If new posts appear between page one and page two, OFFSET 20 can repeat or skip rows; a cursor over (created_at, id) is safer.', 'Choose pagination based on how the collection changes.'),
    ],
    quiz: [
      q('api-en-q1', 'A payment request times out and the client retries. What prevents a double charge?', 'An idempotency key tied to the operation result', 'A longer button label', 'A random new endpoint every retry', 'Offset pagination', 'The server can return the original result for the same logical operation.', 'idempotency'),
      q('api-en-q2', 'Why use a cursor for a changing feed?', 'It continues after a stable ordered item', 'It always encrypts the payload', 'It removes authorization', 'It makes writes free', 'A stable cursor reduces repeats and skips when new rows arrive.', 'pagination'),
      q('api-en-q3', 'What should GET /orders/{id} check?', 'The caller is allowed to read that order', 'The client prefers green buttons', 'The database has no indexes', 'The order id is short', 'Resource APIs still need authorization at the resource boundary.', 'auth'),
      q('api-en-q4', 'When might RPC be reasonable?', 'Internal service actions with a command-like shape', 'All public resources by default', 'Only image files', 'Never under any condition', 'RPC can be fine when the operation is not naturally resource-oriented.', 'rpc'),
      q('api-en-q5', 'What should rate limiting return when a client exceeds quota?', 'A clear 429 response, often with retry guidance', '200 OK with hidden failure', '404 for all users', 'A database migration', 'The caller needs to know it must slow down or wait.', 'rate-limit'),
    ],
    encounter: encounter('api-mimic', 'Pagination Mimic', 'mimic', 'A feed changes between page reads and exposes weak API contracts.', [
      { prompt: 'Which pagination model do you choose for a live feed?', context: 'New posts arrive while users scroll.', tag: 'pagination', good: 'Use cursor pagination with deterministic ordering', bad: 'Use offset only and ignore inserts', goodFeedback: 'The next page is tied to a stable boundary.', badFeedback: 'Rows can repeat or disappear between pages.' },
      { prompt: 'How do you handle create retries?', context: 'The client times out after sending a create request.', tag: 'idempotency', good: 'Accept an idempotency key and replay the stored result', bad: 'Create a new item on every retry', goodFeedback: 'Retries become safe for the client.', badFeedback: 'The same intent can create duplicates.' },
      { prompt: 'How do you expose errors?', context: 'Clients need to correct bad input and respect limits.', tag: 'errors', good: 'Return specific status codes and structured error bodies', bad: 'Return 200 with an error string for everything', goodFeedback: 'The contract is easier to integrate and debug.', badFeedback: 'Clients cannot reliably decide what to do next.' },
    ], 'Describe one endpoint, its retry behavior, pagination model and authorization rule.'),
  },
  'data-modeling': {
    sections: [
      section('Model from access patterns and invariants', 'Start with entities, relationships, query shapes and correctness rules. Relational, document, key-value, wide-column and graph stores each fit different constraints.', 'Orders, payments and inventory often need transactions and constraints. A product search view may be denormalized for read speed.', 'Choose storage from behavior and invariants.'),
      section('Duplicate data deliberately', 'Normalization reduces update paths. Denormalization speeds reads but requires ownership and sync rules. Some copied-looking data is really history and should not be updated.', 'The price on an invoice should stay as it was at purchase time, even if the product price changes later.', 'State which data is current truth and which data is historical snapshot.'),
    ],
    quiz: [
      q('data-en-q1', 'A product price changes today. What price should last month invoice show?', 'The price captured in the order line at purchase time', 'The current product price joined at read time', 'The highest price ever', 'A price sent by the client', 'Purchase price is historical fact.', 'snapshot'),
      q('data-en-q2', 'Why not embed every order ever inside a customer document?', 'The nested set can grow without bound and become hard to update', 'Documents cannot hold numbers', 'SQL requires images in every row', 'One-to-many relationships are forbidden', 'Embedding works best when the contained set is bounded and read together.', 'model-boundary'),
      q('data-en-q3', 'What protects the invariant that inventory is reduced when an order is created?', 'A transaction or clear coordination protocol', 'Two unrelated writes with no repair path', 'An index on product color', 'Renaming Order to Receipt', 'Related state changes need an atomic boundary or recovery protocol.', 'atomicity'),
      q('data-en-q4', 'A best-seller list stores copied product names. What else is required?', 'Source of truth, update mechanism and tolerated staleness', 'A promise copied data is magically never stale', 'Removing product IDs', 'Every copy becomes independent truth', 'Denormalization trades read speed for sync responsibility.', 'denormalization'),
      q('data-en-q5', 'Orders need relationships and multi-row transactions. What is a reasonable starting point?', 'Consider a relational store and validate the real load', 'SQL can never scale', 'NoSQL always makes all writes atomic', 'The number of tables determines SLA', 'Pick based on queries and invariants, then measure.', 'storage-choice'),
    ],
    encounter: encounter('data-golem', 'Relational Golem', 'golem', 'An order system must preserve invoices and avoid negative inventory.', [
      { prompt: 'How should orders store product price?', context: 'Product prices can change after shipment.', tag: 'snapshot', good: 'Store purchase price on the order line', bad: 'Always join the current product price onto old invoices', goodFeedback: 'Historical invoices remain stable.', badFeedback: 'Old invoices can silently change meaning.' },
      { prompt: 'How do you write the last two units of inventory?', context: 'Multiple buyers can race.', tag: 'atomicity', good: 'Conditionally decrement inventory in the order transaction', bad: 'Create orders first and reconcile at the end of the day', goodFeedback: 'Contention is decided at the source of truth.', badFeedback: 'The system can promise stock it does not have.' },
      { prompt: 'How do you maintain copied product names in a read model?', context: 'Name changes can be slightly delayed.', tag: 'denormalization', good: 'Keep productId and update copies from a versioned source', bad: 'Let each list edit names independently', goodFeedback: 'The copy has an owner and repair path.', badFeedback: 'Multiple truths drift apart.' },
    ], 'Name one invariant, one critical query and one intentional snapshot in your model.'),
  },
  caching: {
    sections: [
      section('Cache copies, not truth', 'Cache-aside reads cache first, reads the source on miss and fills the cache. TTL controls freshness; eviction controls memory pressure. The source of truth still decides correctness.', 'A product description can be cached for sixty seconds, but final inventory must be checked in the database transaction.', 'Draw hit, miss and source-of-truth paths.'),
      section('Handle stampedes and hot keys', 'A cache stampede happens when many requests rebuild the same missing key. Single-flight and TTL jitter help. A hot key is different: the key may hit cache but overload one node.', 'If a famous product expires from cache, let one request refill while others wait with a deadline.', 'Separate expiration storms from uneven request distribution.'),
    ],
    quiz: [
      q('cache-en-q1', 'In cache-aside, who usually reads the source and fills cache on miss?', 'The application handling the request', 'DNS', 'The browser reading the database directly', 'An L4 load balancer', 'The app owns miss handling in cache-aside.', 'cache-aside'),
      q('cache-en-q2', 'A cached description must refresh after 60 seconds. What mechanism applies?', 'TTL', 'Only LRU', 'Only more RAM', 'Hashing productId each read', 'TTL handles expiration; LRU handles eviction under pressure.', 'ttl'),
      q('cache-en-q3', 'Eight hundred requests rebuild one expired key. What helps directly?', 'Single-flight for that key', 'Immediate retries from every client', 'Turning off cache everywhere', 'Giving every key the same TTL', 'Single-flight collapses duplicate rebuild work.', 'stampede'),
      q('cache-en-q4', 'Hit rate is high but one cache node is overloaded. What should you inspect?', 'Per-key traffic and read distribution', 'Only TTL for unused keys', 'Only the number of keys', 'The number of domains', 'Request skew can overload a cache even with high hit rate.', 'hot-key'),
      q('cache-en-q5', 'Cache says one item remains. What must final purchase do?', 'Check and decrement inventory atomically at the source of truth', 'Trust cache because it is fresh', 'Delete all old orders', 'Set TTL to infinity', 'Fresh copies still cannot resolve concurrent purchases.', 'consistency'),
    ],
    encounter: encounter('cache-mold', 'Stale Data Mold', 'mold', 'Cached reads improve latency while stale data and stampedes threaten correctness.', [
      { prompt: 'What do you cache first?', context: 'Product descriptions are read repeatedly.', tag: 'cache-aside', good: 'Cache descriptions and keep the database as truth', bad: 'Store confirmed orders only in cache', goodFeedback: 'Repeated reads get faster without risking durable state.', badFeedback: 'Eviction or restart can lose promised orders.' },
      { prompt: 'What happens when a popular key expires?', context: 'Hundreds of requests miss at once.', tag: 'stampede', good: 'Use single-flight with timeout and bounded waiting', bad: 'Let every request rebuild and retry aggressively', goodFeedback: 'The source handles one rebuild instead of hundreds.', badFeedback: 'Duplicate work overloads the source.' },
      { prompt: 'Where do you decide the last item purchase?', context: 'Two buyers can see the same cached stock value.', tag: 'consistency', good: 'Use an atomic conditional update at the source', bad: 'Accept both purchases because cache was recently refreshed', goodFeedback: 'The invariant is protected.', badFeedback: 'Freshness does not prevent races.' },
    ], 'Explain why TTL, single-flight and inventory transactions solve different problems.'),
  },
  sharding: {
    sections: [
      section('Shard only after finding the limit', 'Horizontal sharding splits rows across independent stores. Replication copies the same data for reads or failover. Sharding adds routing, fanout and rebalancing work.', 'If one database cannot handle write traffic after indexing and schema fixes, sharding by buyerId may help order history reads.', 'Name the bottleneck and the new costs.'),
      section('Shard key is query address', 'A good shard key routes common queries and avoids hot partitions. Range partitioning supports locality but can hot spot. Hashing spreads keys but hurts range queries.', 'Hashing buyerId helps fetch one buyer history. Global revenue needs fanout or a separate aggregate model.', 'Test the key against both common and awkward queries.'),
    ],
    quiz: [
      q('sharding-en-q1', '90% of queries fetch order history by buyerId. What shard key is worth testing?', 'Hash buyerId', 'A boolean isPaid flag', 'Current date for every new order', 'One constant value', 'buyerId routes the common query and has many values.', 'shard-key'),
      q('sharding-en-q2', 'Why can date range sharding hot spot writes?', 'Most new writes land in the current range', 'Old data duplicates every minute', 'Hashing preserves time order', 'Every shard has zero CPU', 'Range locality can concentrate new writes at the tail.', 'hot-shard'),
      q('sharding-en-q3', 'Orders are sharded by buyerId and global revenue is needed every second. What cost appears?', 'Fanout or a separately maintained aggregate', 'One buyer lookup gives global revenue', 'DNS sums shards', 'Freshness no longer matters', 'Queries without the routing key must aggregate across shards or read a derived model.', 'fan-out'),
      q('sharding-en-q4', 'You deploy hash(id)%5 after hash(id)%4. What happens?', 'Many keys now route elsewhere but bytes have not moved', 'All records magically move', 'Only new keys are affected', 'All transactions become cross-region atomic', 'Routing changes do not migrate stored data.', 'resharding'),
      q('sharding-en-q5', 'A celebrity tenant dominates traffic. What can help?', 'Split that tenant with buckets or a special placement strategy', 'Add more small tenants', 'Rename shards', 'Use one global lock for every read', 'Skewed tenants need a skew-aware strategy.', 'hot-partition'),
    ],
    encounter: encounter('shard-ogre', 'Hot Partition Ogre', 'ogre', 'One large tenant breaks an otherwise balanced sharding plan.', [
      { prompt: 'How do you choose the first shard key?', context: 'Most reads are by buyer or tenant.', tag: 'shard-key', good: 'Choose a high-cardinality key that routes common reads', bad: 'Choose a low-cardinality status field', goodFeedback: 'Common traffic can reach one shard.', badFeedback: 'Low cardinality creates huge partitions.' },
      { prompt: 'A celebrity tenant gets 70% of traffic. What changes?', context: 'Hashing tenants still leaves this tenant hot.', tag: 'hot-partition', good: 'Bucket or isolate the hot tenant with routing metadata', bad: 'Add shards without changing placement', goodFeedback: 'The skew is handled directly.', badFeedback: 'The hot tenant remains on one shard.' },
      { prompt: 'How do you move data?', context: 'Clients may cache old routing.', tag: 'resharding', good: 'Copy, catch up changes, verify and switch versioned routing', bad: 'Only change the routing function', goodFeedback: 'Ownership and bytes move together.', badFeedback: 'Requests route to places where data is absent.' },
    ], 'Describe shard key choice, hotspot handling and a migration plan.'),
  },
  hashing: {
    sections: [
      section('Limit movement when membership changes', 'Modulo hashing often remaps many keys when node count changes. Consistent hashing places nodes on a ring so only neighboring key ranges move.', 'Adding one cache node to a ring should move a slice of keys, not most of the cache.', 'Stable ownership matters during scaling and failure.'),
      section('Use virtual nodes and replication', 'Virtual nodes smooth distribution by giving each physical node many positions on the ring. Replication stores copies on multiple successors to survive node loss.', 'A node with fewer virtual nodes may receive too little traffic; a failed node can be served by replicas while ownership is repaired.', 'Balance load and failure domains explicitly.'),
    ],
    quiz: [
      q('hashing-en-q1', 'Why is hash(key)%N painful when N changes?', 'Many keys change owners', 'Keys become encrypted', 'B-trees disappear', 'The network becomes faster', 'Changing N changes bucket assignment for many keys.', 'modulo'),
      q('hashing-en-q2', 'On a hash ring, who owns a key?', 'The next node clockwise from the key hash', 'The nearest DNS server', 'Always node zero', 'The oldest database row', 'Consistent hashing uses ring order to assign ownership.', 'ring'),
      q('hashing-en-q3', 'What do virtual nodes improve?', 'Load balance across physical nodes', 'Strong consistency automatically', 'SQL syntax', 'TLS handshakes', 'More positions per node smooth uneven ring gaps.', 'vnodes'),
      q('hashing-en-q4', 'What does replication on the ring help with?', 'Serving data when a node fails', 'Avoiding all cache misses forever', 'Removing the need for routing', 'Preventing every hot key', 'Copies on successors reduce failure impact.', 'replication'),
      q('hashing-en-q5', 'A hot key overloads one owner. What should you consider?', 'Special handling such as replicated reads or request coalescing', 'Only adding virtual nodes', 'Changing font size', 'Deleting the key', 'Virtual nodes balance many keys, not necessarily one extremely hot key.', 'hot-key'),
    ],
    encounter: encounter('hash-serpent', 'Hash Ring Serpent', 'serpent', 'Nodes join and fail while the system tries to minimize key movement.', [
      { prompt: 'How do you add a node?', context: 'Cache ownership must move gradually.', tag: 'modulo', good: 'Place the node on the ring and move only its ranges', bad: 'Switch every client to hash(key)%newN immediately', goodFeedback: 'Only adjacent ranges move.', badFeedback: 'Most keys may be routed away from their data.' },
      { prompt: 'How do you smooth imbalance?', context: 'One ring gap is much larger than others.', tag: 'vnodes', good: 'Assign many virtual nodes per physical node', bad: 'Hope natural randomness fixes the current gap', goodFeedback: 'Ownership is spread more evenly.', badFeedback: 'The imbalance remains unmeasured.' },
      { prompt: 'What happens when a node fails?', context: 'Reads should continue while repair runs.', tag: 'replication', good: 'Read from replicas on successor nodes and repair ownership', bad: 'Return errors for every key in that range', goodFeedback: 'Availability improves with planned redundancy.', badFeedback: 'One failure removes a whole range.' },
    ], 'Explain modulo movement, ring ownership, virtual nodes and replica behavior.'),
  },
  cap: {
    sections: [
      section('Apply CAP to one operation', 'During a network partition, a distributed system cannot both accept every valid operation everywhere and guarantee one consistent result. The right choice depends on the operation.', 'A feed like can be eventually consistent; a seat booking write may need to reject one side of a partition.', 'State the operation before stating the tradeoff.'),
      section('Use stronger language for correctness', 'Strong consistency, eventual consistency, ACID and PACELC are interview tools only when tied to observable behavior.', 'Inventory must not go negative, so the write path may require quorum or a single leader. Feed counters can lag.', 'Different parts of one product can choose different guarantees.'),
    ],
    quiz: [
      q('cap-en-q1', 'During a partition, what does CAP force you to choose for a write operation?', 'Whether to preserve consistency or availability for that operation', 'Whether to use CSS or HTML', 'Whether DNS has a logo', 'Whether every database is SQL', 'Partition tolerance is assumed once the partition exists.', 'cap'),
      q('cap-en-q2', 'Which operation likely needs stronger consistency?', 'Charging a payment or reserving the last seat', 'Counting feed likes for display', 'Showing an old avatar', 'Loading a help page', 'Money and unique inventory have strict invariants.', 'invariant'),
      q('cap-en-q3', 'What is eventual consistency?', 'Replicas converge later if updates stop and propagation succeeds', 'Every read is always newest', 'No writes can fail', 'All latency is zero', 'Eventual consistency allows temporary divergence.', 'eventual'),
      q('cap-en-q4', 'What does PACELC remind you?', 'Even without partition, latency and consistency can trade off', 'CSS can replace databases', 'Cache removes all failures', 'Indexes are free', 'Coordination can cost latency in normal operation too.', 'pacelc'),
      q('cap-en-q5', 'If a minority partition rejects writes, what did you sacrifice?', 'Availability for that write operation', 'All consistency forever', 'Every read globally', 'Storage capacity', 'Rejecting valid writes protects consistency but reduces availability.', 'availability'),
    ],
    encounter: encounter('cap-dragon', 'Network Partition Dragon', 'dragon', 'Different product operations must choose behavior during a partition.', [
      { prompt: 'How should feed reads behave?', context: 'Users can tolerate slightly stale posts.', tag: 'eventual', good: 'Serve local or cached reads with a freshness note', bad: 'Block all feed reads until every region agrees', goodFeedback: 'The user-facing tolerance is used.', badFeedback: 'Availability is lost for a low-risk operation.' },
      { prompt: 'How should payment writes behave?', context: 'Duplicate charges are unacceptable.', tag: 'invariant', good: 'Require the authority or quorum before accepting payment', bad: 'Accept payment independently in every partition', goodFeedback: 'The money invariant is protected.', badFeedback: 'Partitions can create conflicting commitments.' },
      { prompt: 'How should inventory reservations behave?', context: 'Only one buyer can own the last item.', tag: 'consistency', good: 'Reject or queue writes that cannot reach the owner', bad: 'Let every partition reserve the same item', goodFeedback: 'Availability drops only where correctness demands it.', badFeedback: 'The system oversells.' },
    ], 'Compare feed, payment and inventory behavior during a partition.'),
  },
  indexing: {
    sections: [
      section('Index for the query shape', 'Indexes reduce scans by organizing access paths. B-tree, hash, compound, full-text and geospatial indexes solve different queries.', 'WHERE user_id = ? ORDER BY created_at DESC LIMIT 20 often wants a compound index starting with user_id then created_at.', 'The best index follows filters, ordering and cardinality.'),
      section('Indexes cost writes and storage', 'Every index must be updated on writes. Too many or poorly ordered indexes increase write amplification, storage and replication or CDC lag.', 'An index that helped status=open may become useless if almost every row is open.', 'Review indexes as workloads change.'),
    ],
    quiz: [
      q('index-en-q1', 'What does an index primarily avoid?', 'Scanning too many rows for a matching query', 'Storing any data', 'All write costs', 'All network failures', 'Indexes provide faster access paths for matching queries.', 'scan'),
      q('index-en-q2', 'For WHERE user_id=? ORDER BY created_at DESC, what compound order is usually useful?', '(user_id, created_at)', '(created_at, user_id) always', '(is_deleted only)', '(random)', 'Equality on user_id narrows the range before ordering by time.', 'compound'),
      q('index-en-q3', 'What is write amplification from indexes?', 'A write must update extra index structures', 'A read returns fewer rows', 'A cache key gets shorter', 'DNS retries faster', 'Indexes speed reads at the cost of write work and storage.', 'write-cost'),
      q('index-en-q4', 'When is a full-text index relevant?', 'Searching terms inside text', 'Joining two tables by primary key', 'Counting bytes on disk only', 'Assigning a shard owner', 'Text search needs different structures than simple equality lookup.', 'full-text'),
      q('index-en-q5', 'Why can an index become less useful?', 'The workload or selectivity changes', 'B-trees expire every hour', 'Rows stop having IDs', 'The browser changes language', 'Indexes are tied to query shape and data distribution.', 'workload'),
    ],
    encounter: encounter('index-worm', 'Full Scan Worm', 'worm', 'A workload changes and exposes indexes that no longer match queries.', [
      { prompt: 'Which query do you optimize first?', context: 'The slowest user-facing path lists a user orders by time.', tag: 'query-shape', good: 'Index the exact filter and sort path', bad: 'Add a random single-column index', goodFeedback: 'The index matches the access pattern.', badFeedback: 'The scan remains mostly unchanged.' },
      { prompt: 'What do you check before adding five indexes?', context: 'Writes are already close to capacity.', tag: 'write-cost', good: 'Estimate write and storage cost for each index', bad: 'Assume indexes are free because reads get faster', goodFeedback: 'The read gain is balanced against write cost.', badFeedback: 'Writes and CDC can lag.' },
      { prompt: 'A status index stops helping. Why?', context: 'Almost all rows now share the same status.', tag: 'selectivity', good: 'Recheck selectivity and query plans', bad: 'Keep it forever because it was once useful', goodFeedback: 'The index set follows the workload.', badFeedback: 'Maintenance cost stays without read benefit.' },
    ], 'Explain one index choice, its read benefit and its write/storage cost.'),
  },
  numbers: {
    sections: [
      section('Estimate only to change a choice', 'Useful estimates give order-of-magnitude QPS, storage, throughput, latency or headroom. They do not need fake precision.', 'If peak traffic is 150 req/s and one instance handles 60 req/s, two instances are not enough with failure headroom.', 'Use numbers to decide, then name assumptions.'),
      section('Keep units and peaks visible', 'Daily totals hide spikes. Average latency hides tail latency. Storage estimates need retention and replication factors.', 'One million events per day is about 12 per second on average, but a launch spike may be hundreds per second.', 'Always ask what time window the number describes.'),
    ],
    quiz: [
      q('numbers-en-q1', 'Why can daily active users mislead capacity planning?', 'They hide peak request rate and behavior per user', 'They automatically define disk IOPS', 'They remove the need for QPS', 'They guarantee uniform traffic', 'Capacity depends on request rate and burst shape.', 'qps'),
      q('numbers-en-q2', '150 req/s and 60 req/s per replica. How many replicas before headroom?', '3', '1', '2', '10,000', 'ceil(150/60) = 3.', 'capacity'),
      q('numbers-en-q3', 'What should you include in storage estimates?', 'Object size, count, retention and replication factor', 'Only table color', 'Only API version', 'Only DNS TTL', 'Storage grows from size, volume, time and copies.', 'storage'),
      q('numbers-en-q4', 'When should you avoid sharding?', 'When current data and load fit comfortably with headroom', 'Whenever a database exists', 'Whenever reads happen', 'Whenever a diagram has cache', 'Sharding adds cost and should solve a real limit.', 'overengineering'),
      q('numbers-en-q5', 'Why mention p99 latency?', 'It captures tail user experience better than average alone', 'It is always lower than p50', 'It means storage capacity', 'It removes retries', 'Tail latency often drives perceived reliability.', 'latency'),
    ],
    encounter: encounter('numbers-giant', 'Overengineering Giant', 'giant', 'Big numbers tempt premature complexity.', [
      { prompt: 'A service has 20 req/s today. What do you do first?', context: 'No bottleneck is measured yet.', tag: 'overengineering', good: 'Keep the simple design and name scale trigger points', bad: 'Shard every table immediately', goodFeedback: 'The design stays proportional to evidence.', badFeedback: 'Operational cost arrives before the need.' },
      { prompt: 'Peak traffic is 150 req/s. How do you size app replicas?', context: 'One replica handles about 60 req/s in a benchmark.', tag: 'capacity', good: 'Use at least three plus headroom for failures', bad: 'Use one because average traffic is lower', goodFeedback: 'Peak load and headroom are visible.', badFeedback: 'The system fails at the moment users arrive.' },
      { prompt: 'When do numbers matter in the interview?', context: 'Time is limited.', tag: 'estimation', good: 'Calculate when the result changes architecture', bad: 'Spend minutes calculating values that do not affect decisions', goodFeedback: 'Estimation supports design choices.', badFeedback: 'Precision consumes time without improving the answer.' },
    ], 'Estimate QPS, storage or throughput for one decision and state when you would simplify.'),
  },
};

export const englishBosses: Record<string, Encounter> = {
  departure: encounter('departure-boss', 'Twitter Opening Trial', 'scope', 'Open a Twitter-like design in eight minutes and defend the first architecture decisions.', [
    { prompt: 'What do you clarify first?', context: 'The interviewer wants a focused opening.', tag: 'requirements', good: 'Pick core posting, timeline read and follow behavior plus NFRs', bad: 'Start drawing storage engines before requirements', goodFeedback: 'The design now has a target.', badFeedback: 'Technology appears before behavior.' },
    { prompt: 'What entities anchor the design?', context: 'The API needs shared nouns.', tag: 'entities', good: 'User, Tweet, Follow and Timeline are enough to proceed', bad: 'List every analytics and ads object first', goodFeedback: 'The core flow gets vocabulary.', badFeedback: 'Secondary domains crowd the opening.' },
    { prompt: 'Where do you spend deep-dive time?', context: 'Timeline fanout and consistency will shape scale.', tag: 'prioritization', good: 'Deep dive timeline generation and celebrity fanout', bad: 'Spend the rest naming every service', goodFeedback: 'The hard tradeoff is addressed.', badFeedback: 'The risky part remains untested.' },
  ], 'Give your eight-minute opening: requirements, entities, APIs, HLD and one deep dive.'),
  signals: encounter('signals-boss', 'Spaghetti Architecture Hydra', 'hydra', 'A marketplace mixes APIs, entities and data ownership until every inconsistency creates another failure.', [
    { prompt: 'How do you define the create listing flow?', context: 'Listings need ownership, images and searchable state.', tag: 'api', good: 'Define a listing API with owner auth and clear state transitions', bad: 'Let every client write arbitrary database fields', goodFeedback: 'The contract protects ownership and state.', badFeedback: 'Data shape leaks into clients.' },
    { prompt: 'How do you model listing search?', context: 'Search can lag behind the source of truth.', tag: 'data-modeling', good: 'Use a source table plus an eventually updated search model', bad: 'Make search index the only source of truth', goodFeedback: 'Read speed and ownership are separated.', badFeedback: 'A derived index becomes responsible for correctness.' },
    { prompt: 'How do services communicate?', context: 'Images and search updates can happen after listing creation.', tag: 'networking', good: 'Return core success after durable write and process derived work asynchronously', bad: 'Block listing creation on every downstream side effect', goodFeedback: 'The user promise is clear and resilient.', badFeedback: 'Optional work makes the main flow brittle.' },
  ], 'Explain entities, APIs and data ownership for the marketplace without creating inconsistent promises.'),
  scale: encounter('scale-boss', 'Scale Titan', 'titan', 'A ticketing system faces traffic spike, hot key, replica lag and network partition.', [
    { prompt: 'How do you handle the sale launch spike?', context: 'Traffic jumps far above baseline.', tag: 'capacity', good: 'Protect entry with rate limits, queues and measured capacity', bad: 'Let all clients retry the purchase endpoint freely', goodFeedback: 'Demand is shaped before it overloads the core.', badFeedback: 'Retries amplify the spike.' },
    { prompt: 'How do you protect the last seat?', context: 'Only one buyer can own it.', tag: 'consistency', good: 'Reserve through a strongly coordinated owner or transaction', bad: 'Trust cached seat count for final purchase', goodFeedback: 'The invariant is defended.', badFeedback: 'The system can oversell.' },
    { prompt: 'How do you read seat maps during replica lag?', context: 'Users need a useful view, but checkout needs correctness.', tag: 'replication', good: 'Allow slightly stale browsing and check source on checkout', bad: 'Treat every replica read as final truth', goodFeedback: 'Different operations get different guarantees.', badFeedback: 'A stale display becomes a correctness decision.' },
    { prompt: 'What happens during a partition?', context: 'Some regions cannot reach the seat owner.', tag: 'cap', good: 'Reject or queue writes that cannot reach the authority', bad: 'Accept reservations independently in every region', goodFeedback: 'Availability is reduced where correctness requires it.', badFeedback: 'Conflicting reservations appear.' },
    { prompt: 'How do you keep the design proportional?', context: 'The interviewer asks if every component is needed.', tag: 'overengineering', good: 'Tie each component to measured risk and simplify below thresholds', bad: 'Keep every component because big systems have them', goodFeedback: 'The architecture has clear trigger points.', badFeedback: 'Complexity becomes cargo cult.' },
  ], 'Summarize the final architecture, the protected invariants and which parts can be eventually consistent.', 300),
};

export const englishLabs: Record<string, LearningLab> = {
  intro: lab('From memorized answer to decision', 'Switch to requirement-led reasoning and clarify at least 3 questions.', 'Clarifying questions', 'questions', ['Memorized answer', 'Requirement-led reasoning'], (v, m) => ({ headline: m && v >= 3 ? 'Context is clear enough to design' : 'Requirements are still ambiguous', explanation: 'Ask about behavior, scale and consistency before selecting components. Under pushback, tie each choice to one requirement.', nodes: m ? ['Requirements', `${v} clarifications`, 'Assumptions', 'Solution + tradeoff'] : ['Cache + Kafka + shard', 'Why?', 'No basis yet'], goal: m === 1 && v >= 3 }), { max: 5, initial: 0 }),
  delivery: lab('Protect your 45 minutes', 'Choose HLD before deep dive and spend 10-15 minutes on HLD.', 'HLD time', 'minutes', ['Deep dive before HLD', 'HLD before deep dive'], (v, m) => ({ headline: `${45 - 5 - 2 - 5 - v} minutes remain for deep dive and discussion`, explanation: 'Assume 45 minutes: requirements 5, entities 2, API 5. Build a working design before increasing detail.', nodes: m ? ['Requirements 5m', 'Entities 2m', 'API 5m', `HLD ${v}m`, `Deep dive ${33 - v}m`] : ['Requirements', 'Deep dive too early', 'HLD unfinished'], goal: m === 1 && v >= 10 && v <= 15 }), { min: 5, max: 25, initial: 5 }),
  networking: lab('Choose the connection model', 'A scoreboard needs one-way updates under two seconds. Choose SSE.', 'Connections', 'clients', ['Polling every 2s', 'SSE one-way', 'WebSocket two-way'], (v, m) => ({ headline: m === 0 ? `${v / 2} polls/s even without updates` : `${v} long-lived connections to manage`, explanation: m === 1 ? 'SSE fits one-way push; still plan reconnect, resume and capacity.' : 'The model either creates repeated polling work or adds unnecessary bidirectional socket complexity.', nodes: m === 0 ? ['Client', 'Repeated GET', 'Server'] : ['Client', 'Open stream', 'Server events'], goal: m === 1 }), { min: 100, max: 10000, initial: 1000 }),
  api: lab('Paginate changing data', 'Insert at least one item between page reads and switch to cursor.', 'New items before page 2', 'items', ['Offset pagination', 'Cursor by (created_at, id)'], (v, m) => ({ headline: m ? 'Page 2 continues after the last seen item' : `${v} new items can shift OFFSET results`, explanation: m ? 'The cursor points after a stable ordered row.' : 'Offset can repeat or skip rows when the collection changes.', nodes: ['Page 1', `+${v} new`, m ? 'Cursor' : 'OFFSET', 'Page 2'], goal: m === 1 && v > 0 })),
  'data-modeling': lab('Read speed or simple updates?', 'For read-heavy profile names, choose denormalization and set reads to at least 80%.', 'Read ratio', '%', ['Normalized join', 'Copied display name'], (v, m) => ({ headline: m ? `${v} reads avoid joins; ${100 - v} updates sync copies` : `${v} reads require joins; updates stay simple`, explanation: 'Denormalization trades read cost for sync responsibility. Decide from access pattern and staleness tolerance.', nodes: m ? ['Users', 'Copy name', 'Fast read', 'Sync updates'] : ['Users', 'Posts.user_id', 'JOIN'], goal: m === 1 && v >= 80 })),
  caching: lab('Stop a cache stampede', 'Make at least 20 clients miss the same key and enable single-flight.', 'Concurrent clients', 'clients', ['No miss coalescing', 'Single-flight + TTL jitter'], (v, m) => ({ headline: `${m ? 1 : v} database reads for one expired key`, explanation: m ? 'One refill serves many waiting requests.' : 'Every request rebuilds the same value and stresses the source.', nodes: [`${v} requests`, 'MISS', m ? '1 refill' : `${v} refills`, 'DB'], goal: m === 1 && v >= 20 })),
  sharding: lab('Find the hot shard', 'Create a tenant with at least 60% of traffic and split it by bucket.', 'Large tenant traffic', '%', ['Shard by tenant_id', 'tenant_id + bucket'], (v, m) => ({ headline: m ? 'The hot tenant is spread across buckets' : `One shard takes ${v}% of traffic`, explanation: 'Bucketing handles skew but makes whole-tenant queries fan out.', nodes: m ? ['Hot tenant', 'Bucket 0', 'Bucket 1', 'Bucket 2'] : [`Shard hot ${v}%`, 'Shard', 'Shard'], goal: m === 1 && v >= 60 })),
  hashing: lab('Keep old node positions', 'Add a node to the ring instead of changing modulo.', 'New node position', 'degrees', ['Modulo 3 to 4', 'Hash ring'], (v, m) => ({ headline: m ? 'Only the new node range moves' : 'Many keys are remapped', explanation: 'Consistent hashing keeps ownership stable when membership changes.', nodes: m ? ['Old nodes stay', `New node ${v}deg`, 'Partial movement'] : ['3 buckets', 'Change N', '4 buckets'], goal: m === 1 && v > 0 })),
  cap: lab('Partition behavior by operation', 'During a partition, protect seat reservation by requiring the owner or quorum.', 'Partition length', 'seconds', ['Both sides accept writes', 'Owner or quorum writes only'], (v, m) => ({ headline: v === 0 ? 'Network is healthy' : m ? 'Minority side rejects writes' : 'The same seat can be reserved twice', explanation: 'Feed reads and seat reservations can use different consistency guarantees.', nodes: v === 0 ? ['Primary', 'Replica'] : m ? ['Owner accepts', 'Partition', 'Minority rejects'] : ['Side A accepts', 'Partition', 'Side B accepts'], goal: m === 1 && v > 0 })),
  indexing: lab('Index for query shape', 'For user orders by time, choose (user_id, created_at) with at least 10,000 rows.', 'Rows in table', 'rows', ['No index', '(created_at, user_id)', '(user_id, created_at)'], (v, m) => ({ headline: m === 2 ? 'The query can seek into one user range' : 'The database may scan or filter too much', explanation: 'Equality filter first, then time ordering. Indexes still cost writes and storage.', nodes: ['Query', m === 2 ? 'Compound index' : 'Scan/filter', '20 rows'], goal: m === 2 && v >= 10000 }), { min: 1000, max: 100000, initial: 1000 }),
  numbers: lab('Calculate to decide', 'At 150 req/s, choose 30% headroom and compute capacity.', 'Peak traffic', 'req/s', ['No headroom', '30% headroom'], (v, m) => { const n = Math.ceil((m ? v / 0.7 : v) / 60); return { headline: `${n} replicas x 60 = ${n * 60} req/s`, explanation: 'This is a sizing exercise, not a universal server constant. Headroom matters for spikes and failures.', nodes: [`Peak ${v}/s`, m ? 'Utilization <=70%' : 'Utilization <=100%', `${n} replicas`], goal: m === 1 && v === 150 }; }, { min: 60, max: 300, initial: 150 }),
};

export function englishVillage(v: Village): Village {
  return englishBosses[v.id] ? { ...v, boss: englishBosses[v.id] } : v;
}
