import type {Curriculum,ProgressV2} from './types';
import {mastered,parseBackup,STORAGE_KEY} from './progress';
import {escapeHTML as h,notify} from './ui';
export function openJournal(c:Curriculum,p:ProgressV2,replace:(p:ProgressV2)=>void){
  const dialog=document.createElement('dialog');dialog.className='journal-dialog';dialog.setAttribute('aria-label','Sổ hành trình');
  dialog.innerHTML=`<div class="dialog-heading"><div><div class="eyebrow">HẠT MẦM & NHỮNG BÀI HỌC</div><h2>Sổ hành trình</h2></div><button data-close aria-label="Đóng sổ">×</button></div><p>Điểm cao nhất, những tradeoff còn yếu và bản sao tiến độ của bạn.</p>${p.legacyXP?`<p class="legacy">✧ Legacy Explorer XP: ${p.legacyXP}. Kỷ niệm từ làng cũ, không mở khóa Foundation mới.</p>`:''}<div class="journal-list">${c.villages.map(v=>`<h3>${h(v.title)} <small>Boss ${p.bosses[v.id].best}%</small></h3>${v.moduleIds.map(id=>{const m=c.modules.find(m=>m.id===id)!,s=p.modules[id];return`<article><div><b>${mastered(s)?'✦':'♧'} ${h(m.title)}</b><span>Quiz ${s.quizBest}% · Encounter ${s.encounterBest}%</span></div><small>${[s.lesson?'✓ Bài học':'○ Bài học',s.lab?'✓ Lab':'○ Lab',s.reflection?'✓ Giải thích':'○ Giải thích'].join(' · ')}</small>${s.weakTags.length?`<p>Cần ôn: ${s.weakTags.map(h).join(', ')}</p>`:''}</article>`;}).join('')}`).join('')}</div><div class="backup-actions"><button class="primary" data-export>↓ Export JSON</button><label class="secondary file-label">↑ Chọn backup<input type="file" id="backup-file" accept="application/json,.json"></label></div><p class="small">Import thay thế tiến độ trên thiết bị sau khi bạn xem bản tóm tắt. Export trước nếu cần giữ cả hai.</p><div id="import-preview" aria-live="polite"></div>`;
  document.body.append(dialog);dialog.showModal();
  dialog.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  dialog.querySelector<HTMLButtonElement>('[data-export]')!.onclick=()=>{const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hearth-foundation-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  dialog.querySelector<HTMLInputElement>('#backup-file')!.onchange=async event=>{
    const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const preview=dialog.querySelector<HTMLElement>('#import-preview')!;
    try{if(file.size>500000)throw new Error('Backup vượt giới hạn 500 KB.');const next=parseBackup(await file.text(),c);preview.innerHTML=`<div class="import-summary"><b>Backup hợp lệ</b><p>${Object.values(next.modules).filter(mastered).length}/11 module mastery · ${Object.values(next.bosses).filter(b=>b.best>=80).length}/3 boss · ${h(next.updatedAt)}</p><button class="primary" data-confirm-import>Thay thế bằng backup này</button></div>`;preview.querySelector<HTMLButtonElement>('[data-confirm-import]')!.onclick=()=>{
      try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));replace(next);dialog.close();notify('Đã khôi phục tiến độ từ backup.');}catch{preview.textContent='Không thể lưu backup. Tiến độ hiện tại được giữ nguyên.';}
    };}catch(error){preview.textContent=error instanceof Error?error.message:'Không thể đọc tệp.';}
  };
}
