export type Lab={label:string;unit:string;min:number;max:number;value:number;describe:(value:number)=>{title:string;detail:string;nodes:string[]}};
export const labs:Record<string,Lab>={
 gateway:{label:'Request thử gửi trong một giây',unit:'req',min:0,max:300,value:120,describe:n=>({title:`${Math.min(n,180)} nhận · ${Math.max(0,n-180)} bị giới hạn`,detail:'Token bucket giả định có 180 token đầu giây và mỗi request dùng 1 token. Phần dư trả HTTP 429.',nodes:['Client',`${Math.min(n,180)} → Gateway`,n>180?'429 ↩':'200 ✓']})},
 balancer:{label:'Số máy chủ khỏe mạnh',unit:'máy',min:1,max:4,value:2,describe:n=>({title:`120 request chia cho ${n} máy`,detail:'Round robin chia đều một lượt gồm 120 request, giả định request có cùng chi phí.',nodes:Array.from({length:n},(_,i)=>`Server ${i+1}: ${Math.floor(120/n)+(i<120%n?1:0)}`)})},
 compute:{label:'Số replica phục vụ',unit:'máy',min:1,max:4,value:2,describe:n=>({title:`${n*60} req/s năng lực · ${Math.max(0,150-n*60)} req/s quá tải`,detail:'Tải 150 req/s, mỗi máy có năng lực 60 req/s. Cần ít nhất 3 máy; nên có dự phòng để chịu lỗi.',nodes:Array.from({length:n},(_,i)=>`Thỏ ${i+1}: ${Math.min(60,Math.max(0,150-i*60))}/60`)})},
 cache:{label:'Thời gian sau khi cache được điền',unit:'giây',min:0,max:60,value:10,describe:n=>({title:n<30?'Cache HIT':'Cache MISS → đọc DB',detail:'TTL giả định là 30 giây. Sau 30 giây entry hết hạn, lần đọc kế tiếp truy vấn database và điền lại cache.',nodes:n<30?['Client','Sóc Lá · HIT','Trả dữ liệu']:['Client','Sóc Lá · MISS','Rùa Ngọc · DB','Điền cache']})},
 database:{label:'Số người cùng đặt ghế A1',unit:'người',min:1,max:10,value:3,describe:n=>({title:`1 đặt thành công · ${n-1} bị từ chối`,detail:'Mô hình dùng unique constraint cho seat_id và transaction. Chỉ một giao dịch commit; các giao dịch còn lại nhận xung đột, tránh bán trùng ghế.',nodes:Array.from({length:Math.min(n,5)},(_,i)=>i===0?'Txn 1 ✓ COMMIT':`Txn ${i+1} ✕ CONFLICT`)})},
 queue:{label:'Producer gửi mỗi giây',unit:'jobs/s',min:0,max:100,value:40,describe:n=>({title:`${Math.max(0,(n-25)*10)} job chờ sau 10 giây`,detail:'Queue ban đầu rỗng. Worker xử lý 25 job/s. Khi producer nhanh hơn worker, backlog tăng tuyến tính; cần scale consumer hoặc backpressure.',nodes:[`Producer ${n}/s`,'Queue',`Worker 25/s`]})},
 storage:{label:'Dung lượng tệp upload',unit:'MB',min:10,max:100,value:40,describe:n=>({title:`${Math.ceil(n/10)} phần multipart`,detail:'Mỗi phần tối đa 10 MB. Nếu phần thứ hai lỗi, chỉ retry phần đó thay vì tải lại cả tệp. Hoàn tất multipart trước khi phát sự kiện xử lý.',nodes:Array.from({length:Math.min(5,Math.ceil(n/10))},(_,i)=>i===1?'Part 2 ↻ retry':`Part ${i+1} ✓`).concat(Math.ceil(n/10)>5?['…']:[])})},
 cdn:{label:'Tỷ lệ hit tại edge',unit:'%',min:0,max:100,value:75,describe:n=>({title:`${n*2} req/s tại edge · ${(100-n)*2} đến origin`,detail:`Với 200 req/s, edge 8 ms và origin 85 ms, độ trễ trung bình giả định là ${Math.round(n/100*8+(1-n/100)*85)} ms. Đây là trung bình, không phải p95.`,nodes:['200 req/s',`Chim Mây: ${n}% HIT`,`Origin: ${100-n}%`]})},
 shards:{label:'Số shard trên hash ring',unit:'shard',min:2,max:6,value:3,describe:n=>{const buckets=Array(n).fill(0) as number[];for(let key=0;key<24;key++){const hash=(key*137)%360;const idx=Math.ceil(hash/(360/n))%n;buckets[idx]++;}return{title:`24 key trên vòng băm · ${n} shard`,detail:'Key thuộc node kế tiếp theo chiều kim đồng hồ. Thí nghiệm đặt node cách đều trên vòng; thay đổi số node ở đây tái bố trí các node. Trong hệ thống thật nên giữ vị trí node cũ và thêm virtual nodes để hạn chế di chuyển, cân bằng tải.',nodes:buckets.map((count,i)=>`Shard ${i+1}: ${count} key`)}}},
 realtime:{label:'Độ trễ bản sao',unit:'giây',min:0,max:10,value:2,describe:n=>({title:n===0?'Hai bản sao đã hội tụ':`Replica đang trễ ${n} giây`,detail:n===0?'Sau khi cập nhật ngừng và đường truyền phục hồi, replica nhận đủ sự kiện. Eventual consistency không cam kết đọc được bản mới ngay sau ghi.':'Primary đã ghi giá trị mới. Đọc replica có thể thấy giá trị cũ. Với luồng đặt ghế, cần đọc/ghi có đảm bảo mạnh phù hợp.',nodes:['Primary: v2',n===0?'Sự kiện đã đến':'Sự kiện đang truyền',n===0?'Replica: v2':'Replica: v1']})}
};
