export type LabResult={headline:string;explanation:string;nodes:string[];goal:boolean};
export type LearningLab={title:string;task:string;label:string;min:number;max:number;initial:number;unit:string;modes:string[];run:(value:number,mode:number)=>LabResult};
const hash=(s:string)=>{let v=2166136261;for(const char of s)v=Math.imul(v^char.charCodeAt(0),16777619);return(v>>>0)%360;};
export function ringOwner(key:number,nodes:number[]):number{return [...nodes].sort((a,b)=>a-b).find(n=>n>=key)??Math.min(...nodes);}
export const learningLabs:Record<string,LearningLab>={
  intro:{title:'Từ lời giải thuộc lòng đến quyết định',task:'Chuyển sang giải thích theo requirement và chọn ít nhất 3 yêu cầu cần làm rõ.',label:'Số câu hỏi làm rõ',min:0,max:5,initial:0,unit:'câu',modes:['Đọc lời giải thuộc lòng','Giải thích theo requirement'],run:(v,m)=>({headline:m&&v>=3?'Đã xác định bối cảnh để thiết kế':'Requirement còn mơ hồ',explanation:'Bài tập chẩn đoán, không phải điểm dự báo tuyển dụng: hỏi về chức năng, quy mô và consistency trước khi chọn component. Khi bị phản biện, nối quyết định với một yêu cầu cụ thể.',nodes:m?['Yêu cầu',`${v} câu làm rõ`,'Giả định','Giải pháp + tradeoff']:['Cache + Kafka + shard','Vì sao?','Chưa có căn cứ'],goal:m===1&&v>=3})},
  delivery:{title:'Bảo vệ 45 phút của bạn',task:'Chọn HLD trước deep dive và dành 10–15 phút cho HLD.',label:'Thời gian HLD',min:5,max:25,initial:5,unit:'phút',modes:['Deep dive trước HLD','HLD trước deep dive'],run:(v,m)=>({headline:`${45-5-2-5-v} phút còn lại cho deep dive & trao đổi`,explanation:'Khung giả định 45 phút, requirements 5, entities 2, API 5. Data flow chỉ thêm khi có pipeline phức tạp; không tách thêm 5 phút cho mọi đề. Dựng lời giải chạy được trước khi tăng complexity.',nodes:m?['Requirements · 5′','Entities · 2′','API · 5′',`HLD · ${v}′`,`Deep dive · ${33-v}′`]:['Requirements','Deep dive quá sớm','HLD bị bỏ dở'],goal:m===1&&v>=10&&v<=15})},
  networking:{title:'Kết nối theo nhu cầu',task:'Bảng điểm chỉ cần cập nhật một chiều, trễ không quá 2 giây. Chọn SSE và quan sát tải.',label:'Số kết nối',min:100,max:10000,initial:1000,unit:'clients',modes:['Polling mỗi 2 giây','SSE một chiều','WebSocket hai chiều'],run:(v,m)=>({headline:m===0?`${v/2} poll/s dù không có cập nhật`:`${v} kết nối lâu dài cần quản lý`,explanation:m===0?'Polling đơn giản; request vẫn phát sinh khi dữ liệu không đổi.':m===1?'SSE phù hợp một chiều; server phát sự kiện khi có dữ liệu, vẫn cần reconnect, last-event-id và capacity cho kết nối.':'WebSocket phù hợp chat hai chiều; cho bảng điểm một chiều, quản lý socket/protocol có thể dư thừa.',nodes:m===0?['Client','GET lặp lại','Server']:['Client','Kết nối giữ mở','Push sự kiện'],goal:m===1})},
  api:{title:'Trang dữ liệu đang thay đổi',task:'Chèn ít nhất một bài mới giữa hai lần đọc và chuyển sang cursor để tránh lặp.',label:'Bài mới trước trang 2',min:0,max:4,initial:0,unit:'bài',modes:['Offset pagination','Cursor theo (created_at, id)'],run:(v,m)=>({headline:m?'Trang 2: bài 6, 7, 8, 9, 10':`Trang 2: bài ${[6-v,7-v,8-v,9-v,10-v].join(', ')}`,explanation:m?'Cursor ổn định trỏ sau bản ghi cuối trang 1. Cần thứ tự xác định với khóa phụ unique; không tự đảm bảo snapshot nếu bản ghi cũ đổi thứ tự.':`Trang đầu đã đọc bài 1–5. Chèn ${v} bài làm offset dịch; ${v} bài cuối trang 1 có thể lặp ở trang 2.`,nodes:['Trang 1 · 1–5',`+${v} bài mới`,m?'Cursor sau bài 5':'OFFSET 5','Trang 2'],goal:m===1&&v>0})},
  'data-modeling':{title:'Đọc nhanh hay cập nhật đơn giản?',task:'Workload nhiều đọc, ít đổi tên. Chọn denormalize và đặt tỷ lệ đọc ít nhất 80%.',label:'Tỷ lệ đọc',min:0,max:100,initial:50,unit:'%',modes:['Normalized: join Users + Posts','Denormalized: copy display_name'],run:(v,m)=>({headline:m?`${v} lượt đọc gọn · ${100-v} lượt cập nhật phải đồng bộ bản sao`:`${v} lượt đọc join · một nơi cập nhật tên`,explanation:'Mỗi 100 operation giả định. Denormalization giảm join nhưng tăng chi phí cập nhật; dữ liệu lịch sử đơn hàng có thể cố ý giữ snapshot, còn profile cần chính sách đồng bộ. Quyết định theo access pattern, không theo nhãn SQL/NoSQL.',nodes:m?['Users','Copy tên vào Posts','Đọc 1 đường','Cập nhật nhiều nơi']:['Users','Posts.user_id','JOIN khi đọc'],goal:m===1&&v>=80})},
  caching:{title:'Chặn cache stampede',task:'Cho 20 client trở lên cùng gặp miss và bật single-flight.',label:'Client cùng lúc',min:1,max:100,initial:10,unit:'clients',modes:['Cache-aside không gộp miss','Single-flight + TTL jitter'],run:(v,m)=>({headline:`${m?1:v} truy vấn database khi cùng key hết hạn`,explanation:m?'Một lượt nạp cho cùng key, các request khác chờ kết quả. TTL jitter tránh nhiều key hết hạn cùng lúc. Vẫn cần timeout và giới hạn chờ; TTL không thay thế invalidation khi correctness quan trọng.':'Các request thấy miss cùng lúc và đều truy vấn nguồn. DB quá tải có thể kéo dài fill, khiến nhiều request tiếp tục miss.',nodes:[`${v} request`,'MISS',m?'Gộp 1 lượt fill':`${v} lượt fill`,'DB','Cache'],goal:m===1&&v>=20})},
  sharding:{title:'Tìm shard nóng',task:'Tạo tenant chiếm ít nhất 60% traffic, sau đó chia hot tenant bằng composite key.',label:'Traffic tenant lớn',min:25,max:90,initial:25,unit:'%',modes:['Shard theo tenant_id','tenant_id + bucket cho hot tenant'],run:(v,m)=>({headline:m?'Bốn bucket khoảng 25% tải mỗi shard':`Shard nóng ${v}% · các shard còn lại ~${Math.round((100-v)/3)}%`,explanation:m?'Bucketing phân tán hot tenant, đổi lại truy vấn toàn tenant phải fan-out nhiều bucket. Không thay shard key một cách tùy tiện: phải có migration và routing metadata.':'Hash nhiều tenant không giải quyết một tenant quá lớn. Cần xem phân bố tải và query trước khi chọn shard boundary.',nodes:m?['Hot tenant','Bucket 0','Bucket 1','Bucket 2','Bucket 3']:[`Shard 0 · ${v}%`,'Shard 1','Shard 2','Shard 3'],goal:m===1&&v>=60})},
  hashing:{title:'Giữ vị trí node cũ trên vòng băm',task:'Thêm node vào hash ring thay vì modulo; quan sát key di chuyển.',label:'Vị trí node mới',min:1,max:359,initial:45,unit:'độ',modes:['Modulo 3 → 4 node','Hash ring giữ node cũ'],run:(v,m)=>{
    const old=[0,120,240],next=[...new Set([...old,v])];let moved=0;const buckets=Array(next.length).fill(0);
    for(let i=0;i<120;i++){const k=hash(`key-${i}`);const before=m?ringOwner(k,old):k%3;const after=m?ringOwner(k,next):k%4;if(before!==after)moved++;if(m)buckets[next.indexOf(after)]++;}
    return{headline:`${moved}/120 key đổi chủ`,explanation:m?'Node cũ giữ nguyên vị trí. Chỉ đoạn trước node mới chuyển chủ; phân bố có thể lệch, virtual nodes giúp cân bằng. Đây là phân bổ ownership, chưa phải replication.':'Đổi N trong hash % N khiến nhiều key đổi bucket. Không so sánh với cách đặt lại toàn bộ các node trên vòng vì đó không phải thêm node ổn định.',nodes:m?next.map((n,i)=>`Node ${n}° · ${buckets[i]} key`):['3 bucket','Đổi modulo','4 bucket'],goal:m===1&&!old.includes(v)};
  }},
  cap:{title:'Khi hai phía không nghe thấy nhau',task:'Mô phỏng partition trên thao tác giữ ghế: chọn dừng phía không thể phối hợp để bảo vệ invariant.',label:'Partition kéo dài',min:0,max:30,initial:0,unit:'giây',modes:['Cả hai phía nhận giữ ghế','Chỉ leader/quorum được ghi'],run:(v,m)=>({headline:v===0?'Mạng bình thường':m?'Phía thiểu số từ chối ghi':'Có thể xác nhận trùng ghế',explanation:v===0?'Ngoài partition, consistency thường đánh đổi với latency do phối hợp (PACELC).':m?'Bảo vệ một chủ sở hữu ghế đòi hỏi phối hợp. Phía không đạt quorum từ chối thao tác; mất availability ở thao tác đó. Feed có thể dùng yêu cầu khác.':'Hai phía độc lập có thể cùng bán ghế A1. Phản hồi lỗi không được tính là đáp ứng availability theo CAP cho thao tác đọc/ghi hợp lệ.',nodes:v===0?['Primary ⇄ Replica','Ghế A1 chưa bán']:m?['Leader: A1 ✓','× partition','Minority: từ chối']:['A: A1 ✓','× partition','B: A1 ✓'],goal:m===1&&v>0})},
  indexing:{title:'Index theo hình dạng truy vấn',task:'Truy vấn orders của user theo thời gian. Chọn (user_id, created_at) khi có ít nhất 10.000 dòng.',label:'Số dòng trong bảng',min:1000,max:100000,initial:1000,unit:'rows',modes:['Không có index','(created_at, user_id)','(user_id, created_at)'],run:(v,m)=>({headline:m===2?`~${Math.ceil(Math.log2(v))+20} bước minh họa cho 20 kết quả`:m===1?'Có thể phải lọc nhiều user trong khoảng thời gian':`Có thể đọc ${v.toLocaleString('vi')} dòng`,explanation:'Giả định WHERE user_id = ? ORDER BY created_at DESC LIMIT 20. Đặt equality key trước giúp thu hẹp range. Mô hình bước là minh họa, không dự báo số IO thực. Index chiếm dung lượng và làm write cập nhật thêm cấu trúc.',nodes:['Query user + time',m===2?'B-tree prefix user':m===1?'Range time, filter user':'Full scan','20 orders'],goal:m===2&&v>=10000})},
  numbers:{title:'Tính để quyết định',task:'Với peak 150 req/s, chọn headroom 30% và tính năng lực cần thiết.',label:'Peak traffic',min:60,max:300,initial:150,unit:'req/s',modes:['Không headroom','Dự phòng 30% capacity'],run:(v,m)=>{
    const capacity=m?Math.ceil(v/0.7):v,n=Math.ceil(capacity/60);
    return{headline:`${n} replica × 60 = ${n*60} req/s`,explanation:`Giả định benchmark của ứng dụng là 60 req/s/máy; ${m?'mục tiêu sử dụng tối đa 70%':'chạy sát capacity'}. ${m?`ceil(${v}/0,7/60) = ${n}`:`ceil(${v}/60) = ${n}`}. Đây không phải hằng số của mọi server. Thử mất một replica để xem tổng capacity ${Math.max(0,n-1)*60} req/s có đủ peak không.`,nodes:[`Peak ${v}/s`,m?'Utilization ≤70%':'Utilization ≤100%',`${n} replica`],goal:m===1&&v===150};
  }},
};
