import './style.css';
import {lessons} from './content';
import {labs} from './labs';
import {createVillage} from './village';
import {metrics,type Settings} from './simulation';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let progress:Record<string,number>={};try{const data=JSON.parse(localStorage.getItem('hearth-progress-v1')||'{}');if(data&&typeof data==='object')for(const l of lessons)if(Number.isInteger(data[l.id])&&data[l.id]>=0&&data[l.id]<=2)progress[l.id]=data[l.id];}catch{/* Storage is optional. */}
let selected=lessons[0],tab='lesson',question=0,answers:number[]=[],checked=false,paused=false,night=false,backlog=0;
const settings:Settings={load:60,replicas:2,cache:true,failure:false,scenario:'read'};
$('#app').innerHTML=`
<header><a class="brand" href="./"><span class="brand-mark">✿</span> hearth<span class="brand-dot">.</span></a><div class="header-divider"></div><span class="brand-sub">SYSTEM DESIGN VILLAGE</span><nav><button class="nav-active" id="explore">◈ <span>Khám phá</span></button><button id="journal">▤ <span>Sổ hành trình</span></button></nav><div class="xp"><span>✧</span><b id="xp">0 XP</b></div><div class="avatar">HB</div></header>
<main><aside class="sidebar"><div class="eyebrow">MỘT HÀNH TRÌNH NHỎ</div><h1>Xây kiến thức.<br>Nuôi thế giới.</h1><p class="intro">Học kiến trúc hệ thống qua một ngôi làng đầy phép màu.</p><div class="progress-card"><div><span>Nhà kiến trúc tập sự</span><b id="completion">0/10</b></div><div class="progress-track"><i id="progress-fill"></i></div><small id="progress-caption">Mỗi kiến thức, một hạt mầm.</small></div><div class="list-heading"><span>CÔNG TRÌNH TRONG LÀNG</span><span>10</span></div><div id="module-list"></div><a class="source-card" href="https://www.hellointerview.com/learn/system-design/in-a-hurry/introduction" target="_blank" rel="noreferrer"><span>✳</span><div>Học từ những nền tảng tốt<small>Tham khảo Hello Interview ↗</small></div></a></aside>
<section class="center"><div class="world-heading"><div><div class="eyebrow">CHƯƠNG 01 · NHỮNG NỀN MÓNG</div><h2>Làng Khởi Nguyên <span>✦</span></h2></div><button id="day" class="weather">☀ <span>Ngày nắng</span></button></div><div class="world-wrap"><div id="world"></div><div class="map-badge"><i></i> THẾ GIỚI ĐANG SỐNG</div><div class="map-tools"><button id="zoom-in" aria-label="Phóng to">+</button><button id="zoom-out" aria-label="Thu nhỏ">−</button><button id="reset-camera" aria-label="Đặt lại góc nhìn">⌖</button></div><div class="map-hint">↔ Kéo để xoay <span>·</span> Cuộn để thu phóng <span>·</span> Chạm để khám phá</div></div>
<div class="simulation"><div class="sim-title"><div><span class="live-dot"></span><b>Nhịp sống hệ thống</b><span class="pill">LIVE SIMULATION</span></div><button id="pause" class="quiet">Ⅱ Tạm dừng</button></div><div class="stats"><div><small>REQUEST ĐẾN</small><strong id="rate">60 <em>req/s</em></strong><span>Linh thú mang yêu cầu</span></div><div><small>ĐỘ TRỄ TRUNG BÌNH</small><strong id="latency">32 <em>ms</em></strong><span id="health">Hệ thống khỏe mạnh</span></div><div><small>ĐỌC TỪ DATABASE</small><strong id="db">12 <em>req/s</em></strong><span id="cache-stats">Cache đang nghỉ ngơi</span></div><div><small>HÀNG ĐỢI</small><strong id="queue-count">0 <em>jobs</em></strong><span id="errors">0 lỗi · 0 giới hạn/s</span></div></div><div class="sim-controls"><label>Lưu lượng <input id="load" type="range" min="0" max="240" step="10" value="60" aria-label="Lưu lượng request"/><output id="load-value">60/s</output></label><label>Replica <select id="replicas"><option>1</option><option selected>2</option><option>3</option><option>4</option></select></label><label class="toggle"><input id="cache" type="checkbox" checked/> Cache</label><label class="toggle danger"><input id="failure" type="checkbox"/> Sự cố 1 máy</label></div><div class="sim-bottom"><select id="scenario" aria-label="Kịch bản mô phỏng"><option value="read">↗ Kịch bản: Đọc bảng tin</option><option value="upload">↗ Kịch bản: Upload ảnh</option></select><small>Mô hình học tập · tham số giả định</small></div></div><div class="bottom-note"><span>✦ Học bằng cách khám phá, hiểu bằng cách thử nghiệm.</span><span>Được vun trồng bằng sự tò mò ♧</span></div></section>
<aside class="details" id="details"></aside></main><dialog id="journal-dialog"><div class="dialog-head"><div><div class="eyebrow">NHỮNG HẠT MẦM ĐÃ GIEO</div><h2>Sổ hành trình</h2></div><button id="close-journal" aria-label="Đóng sổ">×</button></div><p>Hoàn thành cả hai câu quiz của mỗi công trình để nhận huy hiệu. Kết quả tốt nhất được lưu trên trình duyệt này.</p><div id="journal-content"></div><p class="muted">Nội dung tiếng Việt và câu hỏi được biên soạn riêng, tham khảo các chủ đề công khai của Hello Interview. Đây là dự án độc lập, không liên kết với Hello Interview.</p></dialog><div id="toast" role="status"></div>`;
let village:ReturnType<typeof createVillage>|undefined;
try{village=createVillage($('#world'),select);}catch{ $('#world').innerHTML='<div class="fallback"><h2>Khám phá qua danh sách công trình</h2><p>Trình duyệt này chưa bật WebGL. Các bài học, quiz và bảng mô phỏng vẫn hoạt động đầy đủ.</p></div>'; }
function toast(message:string){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function updateProgress(){const completed=Object.values(progress).filter(n=>n===2).length;$('#xp').textContent=`${Object.values(progress).reduce((a,b)=>a+b,0)*50} XP`;$('#completion').textContent=`${completed}/10`;$('#progress-fill').style.width=`${completed*10}%`;$('#progress-caption').textContent=completed===10?'Cả ngôi làng đã nở hoa. Tuyệt vời!':`${10-completed} công trình đang chờ được khám phá.`;
 $('#module-list').innerHTML=lessons.map((l,i)=>`<button class="module ${l.id===selected.id?'active':''}" data-module="${l.id}"><span class="module-icon" style="--module-color:${l.color}">${l.icon}</span><span><b>${l.name}</b><small>${l.place}</small></span><span class="module-state">${progress[l.id]===2?'✓':String(i+1).padStart(2,'0')}</span></button>`).join('');document.querySelectorAll<HTMLElement>('[data-module]').forEach(b=>b.onclick=()=>select(b.dataset.module!));}
function select(id:string){selected=lessons.find(l=>l.id===id)!;tab='lesson';question=0;answers=[];checked=false;village?.select(id);updateProgress();renderDetails();}
function renderDetails(){const l=selected;$('#details').innerHTML=`<div class="detail-top"><span>ĐANG KHÁM PHÁ</span><span>${String(lessons.indexOf(l)+1).padStart(2,'0')} / 10</span></div><div class="building-art" style="--roof:${l.color}"><div class="art-cloud c1"></div><div class="art-cloud c2"></div><div class="art-island"></div><div class="art-tree t1">♠</div><div class="art-tree t2">♠</div><div class="little-house"><div class="roof"></div><div class="house-body"><div class="window"></div><div class="door"></div><div class="window"></div></div></div><span class="art-spark">✧</span><span class="art-icon">${l.icon}</span></div><div class="detail-body"><div class="eyebrow">${l.place.toLocaleUpperCase('vi')}</div><h2>${l.name}</h2><div class="tags"><span>Nền tảng</span><span>◷ 5 phút</span><span>✧ 100 XP</span></div><div class="tabs" role="tablist"><button id="lesson-tab" role="tab" aria-selected="${tab==='lesson'}" class="${tab==='lesson'?'active':''}">▤ Bài học</button><button id="quiz-tab" role="tab" aria-selected="${tab==='quiz'}" class="${tab==='quiz'?'active':''}">✧ Thử thách <span>2</span></button></div><div id="tab-content"></div></div>`;
 $('#lesson-tab').onclick=()=>{tab='lesson';renderDetails();};$('#quiz-tab').onclick=()=>{tab='quiz';renderDetails();};
 if(tab==='lesson'){$('#tab-content').innerHTML=`<div class="spirit-card"><div class="spirit-face" style="background:${l.color}">•ᴗ•</div><div><b>Gặp ${l.spirit}</b><small>Linh thú hộ mệnh</small></div><span>✦</span></div><p class="role">${l.role}</p><h3>Trong thế giới hệ thống</h3><ul class="concepts">${l.concepts.map(c=>`<li>${c}</li>`).join('')}</ul><div class="tradeoff"><b>⚖ Điều cần cân nhắc</b><p>${l.tradeoff}</p></div><details class="experiment"><summary>⚗ Thử trong ngôi làng</summary><p>${l.experiment}</p></details><div id="module-lab" class="module-lab"></div><a class="read-source" href="https://www.hellointerview.com/learn/system-design/${l.source}" target="_blank" rel="noreferrer">Đọc sâu tại Hello Interview ↗</a><button id="start-quiz" class="primary">Chinh phục thử thách <span>→</span></button>`;renderLab();$('#start-quiz').onclick=()=>{tab='quiz';question=0;answers=[];checked=false;renderDetails();};}else renderQuiz();}
function renderQuiz(){const l=selected;if(question>=l.quiz.length){const score=answers.filter((a,i)=>a===l.quiz[i].answer).length;const best=Math.max(progress[l.id]||0,score);progress[l.id]=best;try{localStorage.setItem('hearth-progress-v1',JSON.stringify(progress));}catch{toast('Không thể lưu trên trình duyệt này. Tiến độ vẫn giữ trong phiên hiện tại.');}updateProgress();$('#tab-content').innerHTML=`<div class="quiz-result"><div>${score===2?'✺':'♧'}</div><h3>${score===2?'Một hạt mầm đã nở!':'Thêm một chút luyện tập'}</h3><p>Bạn trả lời đúng <b>${score}/2</b> câu.<br>Kết quả tốt nhất: ${best}/2 · ${best*50} XP</p><button class="primary" id="retry">Thử lại</button><button class="secondary" id="next-module">Khám phá công trình tiếp theo →</button></div>`;$('#retry').onclick=()=>{question=0;answers=[];checked=false;renderQuiz();};$('#next-module').onclick=()=>select(lessons[(lessons.indexOf(l)+1)%lessons.length].id);return;}
 const q=l.quiz[question];$('#tab-content').innerHTML=`<div class="quiz-caption">THỬ THÁCH ${question+1} / 2 <span>✧ 50 XP</span></div><h3 class="question">${q.q}</h3><div class="answers">${q.options.map((o,i)=>`<button class="answer ${checked?(i===q.answer?'correct':i===answers[question]?'wrong':''):answers[question]===i?'chosen':''}" data-answer="${i}" ${checked?'disabled':''}><span>${String.fromCharCode(65+i)}</span>${o}</button>`).join('')}</div>${checked?`<div class="feedback" role="status"><b>${answers[question]===q.answer?'✓ Chính xác!':'Cùng tìm hiểu nhé'}</b><p>${q.why}</p></div><button class="primary" id="next-question">${question===1?'Xem kết quả':'Câu tiếp theo'} →</button>`:`<button class="primary" id="check-answer" ${answers[question]===undefined?'disabled':''}>Kiểm tra đáp án →</button>`}`;
 document.querySelectorAll<HTMLElement>('[data-answer]').forEach(b=>b.onclick=()=>{answers[question]=Number(b.dataset.answer);renderQuiz();});if(checked)$('#next-question').onclick=()=>{question++;checked=false;renderQuiz();};else $('#check-answer').onclick=()=>{checked=true;renderQuiz();};}
function updateStats(){const m=metrics(settings);$('#rate').innerHTML=`${settings.load} <em>req/s</em>`;$('#latency').innerHTML=`${m.latency} <em>ms</em>`;$('#db').innerHTML=`${m.db} <em>req/s</em>`;$('#queue-count').innerHTML=`${Math.round(backlog)} <em>jobs</em>`;$('#cache-stats').textContent=`${m.edge+m.hits} req/s từ CDN + cache`;$('#errors').textContent=`${m.failed} lỗi · ${m.limited} giới hạn/s`;$('#health').textContent=m.failed?'Có request không được phục vụ':m.limited?'Gateway đang giới hạn tải':'Hệ thống khỏe mạnh';$('#health').classList.toggle('unhealthy',m.failed>0);}
function configure(){settings.load=Number($<HTMLInputElement>('#load').value);settings.replicas=Number($<HTMLSelectElement>('#replicas').value);settings.cache=$<HTMLInputElement>('#cache').checked;settings.failure=$<HTMLInputElement>('#failure').checked;settings.scenario=$<HTMLSelectElement>('#scenario').value as Settings['scenario'];$('#load-value').textContent=`${settings.load}/s`;village?.configure(settings);updateStats();}
['load','replicas','cache','failure','scenario'].forEach(id=>$('#'+id).addEventListener('input',configure));
$('#pause').onclick=()=>{paused=!paused;village?.pause(paused);$('#pause').textContent=paused?'▷ Tiếp tục':'Ⅱ Tạm dừng';$('.map-badge').innerHTML=`<i></i> ${paused?'THẾ GIỚI TẠM NGHỈ':'THẾ GIỚI ĐANG SỐNG'}`;};
$('#day').onclick=()=>{night=!night;village?.night(night);$('#day').innerHTML=night?'☾ <span>Đêm yên bình</span>':'☀ <span>Ngày nắng</span>';};$('#zoom-in').onclick=()=>village?.zoom(.88);$('#zoom-out').onclick=()=>village?.zoom(1.12);$('#reset-camera').onclick=()=>village?.reset();
$('#journal').onclick=()=>{$('#journal-content').innerHTML=lessons.map(l=>`<button class="journal-row" data-visit="${l.id}"><span>${l.icon} ${l.name}</span><b>${progress[l.id]===2?'✦ Hoàn thành':`${progress[l.id]||0}/2 câu đúng`}</b></button>`).join('');$<HTMLDialogElement>('#journal-dialog').showModal();document.querySelectorAll<HTMLElement>('[data-visit]').forEach(b=>b.onclick=()=>{$<HTMLDialogElement>('#journal-dialog').close();select(b.dataset.visit!);});};$('#close-journal').onclick=()=>$<HTMLDialogElement>('#journal-dialog').close();$('#explore').onclick=()=>{village?.reset();$('#world').scrollIntoView({behavior:'smooth',block:'center'});};
setInterval(()=>{if(!paused){backlog=Math.max(0,backlog+metrics(settings).jobs-25);updateStats();}},1000);updateProgress();renderDetails();updateStats();

function renderLab(){const lab=labs[selected.id];const host=$('#module-lab');host.innerHTML=`<div class="lab-heading">⚗ PHÒNG THÍ NGHIỆM</div><label for="lab-value">${lab.label}</label><div class="lab-slider"><input type="range" id="lab-value" min="${lab.min}" max="${lab.max}" value="${lab.value}"/><output id="lab-output"></output></div><div id="lab-result" aria-live="polite"></div>`;function draw(){const value=Number($<HTMLInputElement>('#lab-value').value),result=lab.describe(value);$('#lab-output').textContent=`${value} ${lab.unit}`;$('#lab-result').innerHTML=`<strong>${result.title}</strong><div class="lab-nodes">${result.nodes.map(n=>`<span>${n}</span>`).join('<i>→</i>')}</div><p>${result.detail}</p>`;}$('#lab-value').oninput=draw;draw();}
