import type {Curriculum,ProgressV2} from './types';
import {bossReady,foundationComplete,mastered,recommended} from './progress';
import {escapeHTML as h} from './ui';
import {text,villageView,type Locale} from './locale';
export function renderWorld(host:HTMLElement,c:Curriculum,p:ProgressV2,locale:Locale='vi'){
  const count=c.modules.filter(m=>mastered(p.modules[m.id])).length;
  const labels=locale==='en'?{eyebrow:'A SMALL WORLD. BIG IDEAS.',heading:'The journey of<br>an architect<span>.</span>',intro:'Travel through each village, face tradeoffs<br>and learn to lead a System Design interview.',continue:'Continue journey',review:'✦ Review Foundation',chapter:'THREE VILLAGES · ONE STRONG FOUNDATION',browse:'All Foundation villages are open for reading. Follow the quest arrow when you want to practice in order.',future:'Beyond the horizon',futureSub:'The next chapters of the Hello Interview roadmap',enter:'Read and enter village',reading:'♧ Open for reading'}:{eyebrow:'MỘT THẾ GIỚI NHỎ. NHỮNG Ý TƯỞNG LỚN.',heading:'Hành trình của<br>một nhà kiến trúc<span>.</span>',intro:'Đi qua từng ngôi làng, đối mặt những đánh đổi<br>và học cách dẫn dắt một buổi System Design interview.',continue:'Tiếp tục hành trình',review:'✦ Ôn lại Foundation',chapter:'Ba ngôi làng, một nền tảng vững vàng',browse:'Ba làng Foundation luôn mở để bạn đọc trước. Hãy đi theo mũi tên gợi ý khi muốn luyện theo đúng thứ tự.',future:'Phía bên kia chân trời',futureSub:'Những chương tiếp theo của lộ trình Hello Interview',enter:'Đọc và bước vào làng',reading:'♧ Có thể đọc trước'};
  host.innerHTML=`<div class="world-intro"><div><div class="eyebrow">${labels.eyebrow}</div><h1>${labels.heading}</h1><p>${labels.intro}</p><a class="primary inline" href="${recommended(c,p)}">${foundationComplete(c,p)?labels.review:labels.continue} <span>→</span></a></div><div class="hero-emblem"><div class="compass">✥</div><span>FOUNDATION</span><b>${count}<small> / 11</small></b><p>${locale==='en'?'knowledge seeds':'hạt mầm kiến thức'}</p></div></div><div class="chapter-heading"><h2>${labels.chapter}</h2><span>${locale==='en'?'CHAPTER 01 · OPEN READING':'CHƯƠNG 01 · ĐỌC TỰ DO'}</span></div><p class="browse-note">${labels.browse}</p><div class="world-cards">${c.villages.map((v,i)=>{const vv=villageView(v,locale),done=v.moduleIds.filter(id=>mastered(p.modules[id])).length;return `<article class="village-card ${v.biome}"><div class="island-preview"><div class="island-earth"></div><div class="map-tree tree-left">♠</div><div class="map-tree tree-right">♠</div><div class="map-house"><i style="background:${v.color}"></i><b><em></em></b></div><div class="map-tower"><i style="background:${v.color}"></i><b></b></div><span class="island-star">${p.bosses[v.id].best>=80?'✦':'↗'}</span><span class="island-number">0${i+1}</span></div><div class="village-card-body"><div class="eyebrow">${h(vv.subtitle)}</div><h3>${h(vv.title)}</h3><p>${h(vv.description)}</p><div class="village-progress"><span>${done}/${v.moduleIds.length} ${locale==='en'?'modules':'module'}</span><span>${p.bosses[v.id].best>=80?'✦ '+(locale==='en'?'Boss defeated':'Boss đã vượt'):bossReady(c,p,v.id)?'⚔ '+(locale==='en'?'Boss ready':'Boss sẵn sàng'):labels.reading}</span></div><div class="progress-bar"><i style="width:${done/v.moduleIds.length*100}%"></i></div><a class="village-entry" href="#/village/${v.id}">${labels.enter} <span>↗</span></a></div></article>`;}).join('')}</div><div class="future-heading"><h2>${labels.future}</h2><p>${labels.futureSub}</p></div><div class="future-regions"><article><span>▥</span><div><h3>Technologies <small>⌑ Coming soon</small></h3><p>${locale==='en'?'System building tools':'Công cụ xây dựng hệ thống'}</p><small>Redis, PostgreSQL, Kafka, search & storage</small></div></article><article><span>⌘</span><div><h3>Patterns <small>⌑ Coming soon</small></h3><p>${locale==='en'?'Recognize and combine solutions':'Nhận diện và kết hợp giải pháp'}</p><small>Scaling, contention, realtime & workflows</small></div></article><article><span>⚑</span><div><h3>Practice <small>⌑ Coming soon</small></h3><p>${locale==='en'?'Interview arena':'Đấu trường phỏng vấn'}</p><small>Deep dives and mock interviews</small></div></article></div><p class="source-note">Foundation curriculum based on <a href="https://www.hellointerview.com/learn/system-design/in-a-hurry/how-to-prepare" target="_blank" rel="noreferrer">Hello Interview ↗</a>. ${locale==='en'?'Hearth lessons and challenges are original.':'Bài học và thử thách tiếng Việt được biên soạn riêng.'}</p>`;
}
