/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalIndexRouteImport } from './routes/technical/index'
import { Route as PersonalIndexRouteImport } from './routes/personal/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiUnsplashRouteImport } from './routes/api/unsplash'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalIndexRoute = TechnicalIndexRouteImport.update({
  id: '/technical/',
  path: '/technical/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalIndexRoute = PersonalIndexRouteImport.update({
  id: '/personal/',
  path: '/personal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsplashRoute = ApiUnsplashRouteImport.update({
  id: '/api/unsplash',
  path: '/api/unsplash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/api/unsplash': typeof ApiUnsplashRoute
  '/blog/$': typeof BlogSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/personal/': typeof PersonalIndexRoute
  '/technical/': typeof TechnicalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/api/unsplash': typeof ApiUnsplashRoute
  '/blog/$': typeof BlogSplatRoute
  '/admin': typeof AdminIndexRoute
  '/personal': typeof PersonalIndexRoute
  '/technical': typeof TechnicalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/api/unsplash': typeof ApiUnsplashRoute
  '/blog/$': typeof BlogSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/personal/': typeof PersonalIndexRoute
  '/technical/': typeof TechnicalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/search'
    | '/api/unsplash'
    | '/blog/$'
    | '/admin/'
    | '/personal/'
    | '/technical/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/search'
    | '/api/unsplash'
    | '/blog/$'
    | '/admin'
    | '/personal'
    | '/technical'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/search'
    | '/api/unsplash'
    | '/blog/$'
    | '/admin/'
    | '/personal/'
    | '/technical/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUnsplashRoute: typeof ApiUnsplashRoute
  BlogSplatRoute: typeof BlogSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PersonalIndexRoute: typeof PersonalIndexRoute
  TechnicalIndexRoute: typeof TechnicalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/': {
      id: '/technical/'
      path: '/technical'
      fullPath: '/technical/'
      preLoaderRoute: typeof TechnicalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/': {
      id: '/personal/'
      path: '/personal'
      fullPath: '/personal/'
      preLoaderRoute: typeof PersonalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsplash': {
      id: '/api/unsplash'
      path: '/api/unsplash'
      fullPath: '/api/unsplash'
      preLoaderRoute: typeof ApiUnsplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUnsplashRoute: ApiUnsplashRoute,
  BlogSplatRoute: BlogSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  PersonalIndexRoute: PersonalIndexRoute,
  TechnicalIndexRoute: TechnicalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
